# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "camel.apache.org/v1alpha1",
          "kind": "CamelMonitor",
          "metadata": {
            "labels": {
              "app": "camel-monitor-operator"
            },
            "name": "example"
          },
          "spec": {}
        }
      ]
    capabilities: Full Lifecycle
    categories: Integration & Delivery
    certified: "false"
    containerImage: quay.io/camel-tooling/camel-monitor-operator:0.3.0-SNAPSHOT
    createdAt: "2026-05-20T09:06:54Z"
    description: Camel Monitor Operator is the monitoring tool for your Apache Camel
      applications running on cloud.
    operators.operatorframework.io/builder: operator-sdk-v1.30.0
    operators.operatorframework.io/internal-objects: '["camelmonitors.camel.apache.org"]'
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
    repository: https://github.com/camel-tooling/camel-monitor-operator
    support: Camel
  name: camel-monitor-operator.v0.3.0
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CamelMonitor is the Schema for the CamelMonitor API
      displayName: CamelMonitor
      kind: CamelMonitor
      name: camelmonitors.camel.apache.org
      version: v1alpha1
  description: |
    Camel Monitor Operator
    ==============

    Camel Monitor Operator is the monitoring tool for your Apache Camel applications running on cloud.

    ## Installation

    Proceed to the Camel Monitor operator installation via `Subscription` or via GUI.
    See official Camel Monitor operator documentation to learn how to configure all the available parameters.

    ## Monitoring an Apache Camel Application

    Run an Apache Camel application on the cluster (for example via Apache Camel K operator). Immediately you will be able to see a `CamelMonitor`:

    ```
    kubectl get camelmonitors -w

    NAME        INFO                        PHASE     REPLICAS   HEALTHY   MONITORED   MEMORY PRESSURE   CPU PRESSURE   EXCHANGE SLI   LAST EXCHANGE
    sample-it   Quarkus - 3.30.8 (4.16.0)   Running   1          True      True        False             False          Success        1s
    sample-it   Quarkus - 3.30.8 (4.16.0)   Paused    0          Unknown   Unknown                                      Success        61s
    ...
    ```
  displayName: Camel Monitor Operator
  icon:
  - base64data: PHN2ZyB2aWV3Qm94PSIwIDAgMTMwLjIxIDEzMC4wMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImEiIHgxPSIzMzMuNDgiIHgyPSI0NzciIHkxPSI3MDIuNiIgeTI9IjU2My43MyIgZ3JhZGllbnRUcmFuc2Zvcm09InRyYW5zbGF0ZSg5NC4wMzggMjc2LjA2KSBzY2FsZSguOTkyMDYpIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHN0b3Agc3RvcC1jb2xvcj0iI0Y2OTkyMyIgb2Zmc2V0PSIwIi8+PHN0b3Agc3RvcC1jb2xvcj0iI0Y3OUEyMyIgb2Zmc2V0PSIuMTEiLz48c3RvcCBzdG9wLWNvbG9yPSIjRTk3ODI2IiBvZmZzZXQ9Ii45NDUiLz48L2xpbmVhckdyYWRpZW50PjxsaW5lYXJHcmFkaWVudCBpZD0iYiIgeDE9IjMzMy40OCIgeDI9IjQ3NyIgeTE9IjcwMi42IiB5Mj0iNTYzLjczIiBncmFkaWVudFRyYW5zZm9ybT0idHJhbnNsYXRlKDk0LjAzOCAyNzYuMDYpIHNjYWxlKC45OTIwNikiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjRjY5OTIzIiBvZmZzZXQ9IjAiLz48c3RvcCBzdG9wLWNvbG9yPSIjRjc5QTIzIiBvZmZzZXQ9Ii4wOCIvPjxzdG9wIHN0b3AtY29sb3I9IiNFOTc4MjYiIG9mZnNldD0iLjQxOSIvPjwvbGluZWFyR3JhZGllbnQ+PGxpbmVhckdyYWRpZW50IGlkPSJjIiB4MT0iNjMzLjU1IiB4Mj0iNTY2LjQ3IiB5MT0iODE0LjYiIHkyPSI5MDkuMTIiIGdyYWRpZW50VHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTg1LjQyMSA1Ni4yMzYpIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHN0b3Agc3RvcC1jb2xvcj0iI2Y2ZTQyMyIgb2Zmc2V0PSIwIi8+PHN0b3Agc3RvcC1jb2xvcj0iI0Y3OUEyMyIgb2Zmc2V0PSIuNDEyIi8+PHN0b3Agc3RvcC1jb2xvcj0iI0U5NzgyNiIgb2Zmc2V0PSIuNzMzIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTQzNy44OSAtODM1LjI5KSI+PGNpcmNsZSBjeD0iNTAzLjEiIGN5PSI5MDAuMjkiIHI9IjYyLjUyIiBmaWxsPSJ1cmwoI2EpIiBzdHJva2U9InVybCgjYikiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHN0cm9rZS13aWR0aD0iNC45NiIvPjxwYXRoIGQ9Ik00ODcuODkgODczLjY0YTg5LjUzIDg5LjUzIDAgMCAwLTIuNjg4LjAzMWMtMS4wNDMuMDMxLTIuNDQ1LjM2Mi00LjA2Mi45MDYgMjcuMzA5IDIwLjczNyAzNy4xMjcgNTguMTQ2IDIwLjI1IDkwLjY1Ni41NzMuMDE1IDEuMTQyLjA2MyAxLjcxOS4wNjMgMzAuODQ0IDAgNTYuNjItMjEuNDkzIDYzLjI4LTUwLjMxMi0xOS41NzItMjIuOTQzLTQ2LjExNy00MS4yOTQtNzguNS00MS4zNDR6IiBmaWxsPSJ1cmwoI2MpIiBvcGFjaXR5PSIuNzUiLz48cGF0aCBkPSJNNDgxLjE0IDg3NC41OGMtOS4wNjggMy4wNTItMjYuMzY4IDEzLjgwMi00MyAyOC4xNTYgMS4yNjMgMzQuMTk1IDI4Ljk2MSA2MS42MDcgNjMuMjUgNjIuNSAxNi44NzctMzIuNTEgNy4wNi02OS45MTktMjAuMjUtOTAuNjU2eiIgZmlsbD0iIzI4MTcwYiIgb3BhY2l0eT0iLjc1Ii8+PHBhdGggZD0iTTUwNC44ODkgODYyLjU0NmMtLjQ3Mi0uMDMyLS45MzIuMDI4LTEuMzc1LjI1LTUuNiAyLjgwMSAwIDE0IDAgMTQtMTYuODA3IDE0LjAwOS0xMy4yMzYgMzcuOTM4LTMyLjg0NCAzNy45MzgtMTAuNjg5IDAtMjEuMzIyLTEyLjI5My0zMi41MzEtMTkuODEyLS4xNDQgMS43NzMtLjI1IDMuNTY0LS4yNSA1LjM3NSAwIDI0LjUxNSAxMy41MSA0NS44NjMgMzMuNDY5IDU3LjA2MyA1LjU4My0uNzAzIDExLjE1OC0yLjExNCAxNS4zNDQtNC45MDYgMjEuOTkyLTE0LjY2MiAyNy40NTItNDIuNTU3IDM2LjQzOC01Ni4wMzEgNS41OTYtOC40MDcgMzEuODI0LTcuNjc3IDMzLjU5NC0xMS4yMiAyLjgwNC01LjYwMS01LjYwMi0xNC04LjQwNi0xNGgtMjIuNDA2Yy0xLjU2NiAwLTQuMDI1LTIuNzgtNS41OTQtMi43OGgtOC40MDZzLTMuNzI1LTUuNjUtNy4wMzEtNS44NzV6IiBmaWxsPSIjZmZmIi8+PC9nPjwvc3ZnPg==
    mediatype: image/svg+xml
  install:
    spec:
      deployments:
      - label:
          app: camel-monitor-operator
          app.kubernetes.io/component: operator
          app.kubernetes.io/name: camel-monitor
          app.kubernetes.io/version: 0.3.0-SNAPSHOT
          camel.apache.org/component: operator
          name: camel-monitor-operator
        name: camel-monitor-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: camel-monitor-operator
              name: camel-monitor-operator
          strategy:
            type: Recreate
          template:
            metadata:
              labels:
                app: camel-monitor-operator
                app.kubernetes.io/component: operator
                app.kubernetes.io/name: camel-monitor
                app.kubernetes.io/version: 0.3.0-SNAPSHOT
                camel.apache.org/component: operator
                name: camel-monitor-operator
            spec:
              containers:
              - command:
                - camel-monitor
                - operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: OPERATOR_NAME
                  value: camel-monitor
                - name: OPERATOR_ID
                  value: camel-monitor
                - name: CREATE_PROMETHEUS_POD_MONITOR
                  value: "true"
                - name: CREATE_PROMETHEUS_RULE
                  value: "true"
                - name: CREATE_GRAFANA_DASHBOARD
                  value: "true"
                - name: GRAFANA_DS
                  value: prometheus
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/camel-tooling/camel-monitor-operator:0.3.0-SNAPSHOT
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 20
                  periodSeconds: 10
                name: camel-monitor-operator
                ports:
                - containerPort: 8080
                  name: metrics
                resources:
                  limits:
                    cpu: "1"
                    memory: 1Gi
                  requests:
                    cpu: 250m
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
              serviceAccountName: camel-monitor-operator
      permissions:
      - rules:
        - apiGroups:
          - camel.apache.org
          resources:
          - camelmonitors
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
        - apiGroups:
          - camel.apache.org
          resources:
          - camelmonitors/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - batch
          resources:
          - cronjobs
          - jobs
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          - events.k8s.io
          resources:
          - events
          verbs:
          - create
          - patch
          - get
          - list
          - watch
        - apiGroups:
          - grafana.integreatly.org
          resources:
          - grafanadashboards
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - camel.apache.org
          resources:
          - camelmonitors/finalizers
          verbs:
          - update
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - podmonitors
          - prometheusrules
          verbs:
          - create
          - get
          - list
          - update
          - watch
        serviceAccountName: camel-monitor-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - apache
  - camel
  - kubernetes
  - monitoring
  - microservices
  - integration
  labels:
    name: camel-monitor-operator
  links:
  - name: Camel Monitor operator source code repository
    url: https://github.com/camel-tooling/camel-monitor-operator
  maintainers:
  - email: pcongiusti@apache.org
    name: Pasquale Congiusti
  maturity: alpha
  provider:
    name: Camel Tooling team
  selector:
    matchLabels:
      name: camel-monitor-operator
  version: 0.3.0
